export type Role = "traveler" | "business" | "admin" | "authority";
export type Provenance = {
  provider: string;
  status: "live" | "cached" | "demo" | "unavailable";
  retrievedAt: string | null;
  message?: string;
};
export type Place = {
  id: string;
  name: string;
  city: string;
  category: string;
  subcategory: string;
  address: string;
  lat: number;
  lng: number;
  rating: number;
  reviews: string;
  hours: string;
  cost: number;
  duration: number;
  description: string;
  overview: string;
  image: string;
  hidden: boolean;
  indoor: boolean;
  interests: string[];
  accessibility: string;
  source: string;
};
export type Stay = {
  id: string;
  name: string;
  city: string;
  type: string;
  price: number;
  rating: number;
  location: string;
  image: string;
  amenities: string[];
  veg: boolean;
  lift: boolean;
  senior: boolean;
  water: boolean;
  power: boolean;
  solo: boolean;
  suitableFor: string[];
  reason: string;
  proximity: string;
};
export type Restaurant = {
  id: string;
  name: string;
  city: string;
  cuisine: string;
  rating: number;
  location: string;
  price: number;
  veg: boolean;
  pureVeg: boolean;
  jain: boolean;
  image: string;
  dish: string;
  hours: string;
  tags: string[];
};
export type Experience = {
  id: string;
  title: string;
  city: string;
  category: string;
  host: string;
  duration: string;
  price: number;
  rating: number;
  location: string;
  description: string;
  image: string;
};
export type City = {
  name: string;
  state: string;
  tagline: string;
  image: string;
  lat: number;
  lng: number;
  color: string;
};
export type Preferences = {
  origin: string;
  destination: string;
  startDate: string;
  endDate: string;
  travelers: number;
  group: string;
  budget: number;
  interests: string[];
  food: string;
  transport: string;
  stay: string;
  accessibility: string[];
  request: string;
};
export type Item = {
  id: string;
  placeId: string;
  title: string;
  time: string;
  duration: number;
  cost: number;
  category: string;
  lat: number;
  lng: number;
  image: string;
  indoor: boolean;
  reason: string;
  travelMinutes: number;
  distance: number;
  replaced?: boolean;
  completed?: boolean;
  originalTitle?: string;
};
export type TripDay = {
  number: number;
  date: string;
  title: string;
  items: Item[];
};
export type Trip = {
  id: string;
  title: string;
  preferences: Preferences;
  days: TripDay[];
  estimate: number;
  emergency: number;
  buffer: number;
  breakdown: Record<string, number>;
  source: Provenance;
  notes: string[];
  createdAt: string;
  version: number;
  recoveryIds: string[];
};
export type Profile = {
  name: string;
  email: string;
  phone: string;
  city: string;
  language: string;
  food: string;
  transport: string;
  pace: string;
  interests: string[];
  accessibility: string[];
  emergencyContact: string;
  notifications: boolean;
};
export type Booking = {
  id: string;
  code: string;
  tripId: string | null;
  title: string;
  type: string;
  date: string;
  nights: number;
  guests: number;
  rooms: number;
  amount: number;
  status: "Confirmed" | "Completed" | "Cancelled" | "Refund pending";
  guest: string;
  payment: "demo" | "test" | "live";
  createdAt: string;
  paymentId?: string;
};
export type Expense = {
  id: string;
  tripId: string | null;
  title: string;
  amount: number;
  category: string;
  method: string;
  notes: string;
  date: string;
  bookingId?: string;
};
export type Notice = {
  id: string;
  title: string;
  message: string;
  category: string;
  read: boolean;
  createdAt: string;
  href?: string;
};
export type Stamp = {
  id: string;
  placeId: string;
  name: string;
  city: string;
  xp: number;
  method: string;
  date: string;
  simulated: boolean;
};
export type Business = {
  canManage?: boolean;
  id: string;
  name: string;
  owner: string;
  category: string;
  address: string;
  city: string;
  phone: string;
  status: "Pending" | "Verified" | "Rejected" | "More information";
  document?: string;
  createdAt: string;
  note?: string;
};
export type Offer = {
  id: string;
  businessId: string;
  title: string;
  description: string;
  discount: number;
  price: number;
  food: string;
  location: string;
  lat: number;
  lng: number;
  timeWindow: string;
  target: string;
  active: boolean;
  clicks: number;
  createdAt: string;
  image?: string;
};
export type ChatMessage = {
  id: string;
  role: "user" | "assistant";
  text: string;
  action?: string;
  source?: Provenance;
  date: string;
};
export type SavedRoute = {
  id: string;
  title: string;
  tripId: string;
  day: number;
  favorite: boolean;
  createdAt: string;
};
export type State = {
  profile: Profile;
  role: Role;
  demo: boolean;
  authConfigured: boolean;
  trips: Trip[];
  activeTripId: string | null;
  bookings: Booking[];
  expenses: Expense[];
  notifications: Notice[];
  stamps: Stamp[];
  favorites: string[];
  businesses: Business[];
  offers: Offer[];
  chat: ChatMessage[];
  routes: SavedRoute[];
  onboarding: boolean;
};
export type Catalog = {
  places: Place[];
  stays: Stay[];
  restaurants: Restaurant[];
  experiences: Experience[];
};
export type Weather = {
  city: string;
  temp: number | null;
  condition: string;
  rain: number | null;
  wind: number | null;
  aqi: number | null;
  hourly: { time: string; temp: number; rain: number }[];
  source: Provenance;
};
export type Incident = {
  id: string;
  type: string;
  day: number;
  itemId: string;
  delay: number;
  simulated: boolean;
};
export type Recovery = {
  id: string;
  mode: string;
  title: string;
  description: string;
  costDelta: number;
  timeDelta: number;
  before: number;
  after: number;
  replacements: { before: string; after: string }[];
  days: TripDay[];
  affected: number;
  warnings: string[];
  incident: Incident;
  baseVersion: number;
  tripId: string;
};
